# Alternative:  docker run -d --name rabbitmq-container -p 5672:5672 -p 15672:15672 -v rabbitmq-data:/var/lib/rabbitmq rabbitmq:4-management
# Run this file in detached mode: docker-compose up -d
# To view logs later: docker compose logs

version: '3.8' # version of Docker Compose syntax
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"  # messaging
      - "15672:15672" # management dashboard
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq  # uses an existing volume (rabbitmq-data) within the service.

volumes:
  rabbitmq-data:  # declares the volume (rabbitmq-data) to ensure it is created and managed properly by Docker.