# Alternative:  docker run -d --name redis-container -p 6379:6379 -v redis-data:/data redis:latest redis-server --save 60 1 --loglevel warning
# Run this file in detached mode: docker-compose up -d
# To view logs later: docker compose logs

version: '3.8' # version of Docker Compose syntax
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data  # uses an existing volume (redis-data) within the service.
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

volumes:
  redis-data:  # declares the volume (redis-data) to ensure it is created and managed properly by Docker.