// https://marketplace.visualstudio.com/items/?itemName=humao.rest-client

#INFO https://https://API_ENDPOINT
GET https://https://API_ENDPOINT

Accept: application/json
Content-Type: application/json
#Authorization: Basic ...

{
  
}