// https://marketplace.visualstudio.com/items/?itemName=humao.rest-client
PUT http://localhost:9999/users/1
#Cookie: key1 = value1
#Cookie: key2 = value2
Content-Type: application/json
#Authorization: Basic key...
{
  
}